/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.epam.training.fooddelivery.api;

import com.epam.training.fooddelivery.model.FoodModel;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-08-25T23:29:15.611086100+02:00[Europe/Warsaw]")
@Validated
@Api(value = "foodservice", description = "the foodservice API")
public interface FoodserviceApi {

    /**
     * GET /foodservice/foods : List of all foods
     * List of all foods
     *
     * @return successful operation (status code 200)
     */
    @ApiOperation(value = "List of all foods", nickname = "listAllFoods", notes = "List of all foods", response = FoodModel.class, responseContainer = "List", tags={ "food-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = FoodModel.class, responseContainer = "List") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/foodservice/foods",
        produces = { "application/json" }
    )
    ResponseEntity<List<FoodModel>> listAllFoods();

}
