/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.training.fooddelivery.api;

import com.training.fooddelivery.model.FoodModel;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-08-26T23:41:58.811663200+02:00[Europe/Warsaw]")
@Validated
@Api(value = "foodservice", description = "the foodservice API")
public interface FoodserviceApi {

    /**
     * GET /foodservice/foods : List of all foods
     * List of all foods
     *
     * @return successful operation (status code 200)
     */
    @ApiOperation(value = "List of all foods", nickname = "listAllFoods", notes = "List of all foods", response = FoodModel.class, responseContainer = "List", tags={ "food-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = FoodModel.class, responseContainer = "List") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/foodservice/foods",
        produces = { "application/json" }
    )
    ResponseEntity<List<FoodModel>> listAllFoods();

}
